freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script: pkg install -y postgresql10-server gmake libxml2 autoconf automake libtool pkgconf gettext iconv pcre gdal sfcgal geos

build_script:
  - service postgresql oneinitdb
  - service postgresql onestart
  - su -l postgres -c "createuser -s `whoami`"
  - ./autogen.sh
  - ./configure CFLAGS="-I/usr/local/include -Wall -fno-omit-frame-pointer -Werror" LDFLAGS="-L/usr/local/lib"
  - gmake
