freebsd_instance:
  image: freebsd-12-2-release-amd64
  cpu: 8
  memory: 16G

task:
  timeout_in: 320m
  sysinfo_script:
    - mount
    - df -h
    - sysctl hw.model hw.ncpu hw.physmem
    - freebsd-version

  install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f ; pkg upgrade -y
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y bison postgresql12-server gmake libxml2 autoconf automake libtool pkgconf gettext iconv pcre proj gdal sfcgal geos libxslt cunit protobuf-c json-c postgresql12-contrib gtk2

  build_script:
    # will be removed
    - find . -name "*.pl" | xargs sed -i -r 's|/usr/bin/perl|/usr/bin/env perl|'
    - service postgresql oneinitdb
    - service postgresql onestart
    - su -l postgres -c "createuser -s `whoami`"
    - ./autogen.sh
    - ./configure CFLAGS="-isystem /usr/local/include -Wall -fno-omit-frame-pointer -Werror" LIBS="-L/usr/local/lib" LDFLAGS="-L/usr/local/lib" PKG_CONFIG="/usr/local/bin/pkgconf" --with-libiconv-prefix=/usr/local --with-topology --with-gdalconfig=/usr/local/bin/gdal-config --with-sfcgal=/usr/local/bin/sfcgal-config --with-address-standardizer --with-protobuf --with-wagyu --with-nls
    - gmake -j8
    - gmake -j8 check RUNTESTFLAGS=-v
    - gmake -j8 check RUNTESTFLAGS="-v --dumprestore"
    - gmake -j8 install
    - gmake -j8 installcheck RUNTESTFLAGS=-v
    - gmake -j8 installcheck RUNTESTFLAGS="-v --dumprestore"
