freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script: pkg install -y bison postgresql10-server gmake libxml2 autoconf automake libtool pkgconf gettext iconv pcre gdal sfcgal geos libxslt cunit
  
  build_script:
    # will be removed
    - find . -name "*.pl" | xargs sed -i -r 's|/usr/bin/perl|/usr/bin/env perl|'
    - service postgresql oneinitdb
    - service postgresql onestart
    - su -l postgres -c "createuser -s `whoami`"
    - ./autogen.sh
    - ./configure CFLAGS="-I/usr/local/include -Wall -fno-omit-frame-pointer -Werror" LDFLAGS="-L/usr/local/lib"
    - gmake
    - gmake check RUNTESTFLAGS=-v
    - gmake check RUNTESTFLAGS="-v --dumprestore"
    - gmake install
    - gmake installcheck RUNTESTFLAGS=-v
    - gmake installcheck RUNTESTFLAGS="-v --dumprestore"
