freebsd_instance:
  image: freebsd-12-0-release-amd64
  cpu: 8
  memory: 16G

task:
  timeout_in: 320m
  sysinfo_script:
    - mount
    - df -h
    - sysctl hw.model hw.ncpu hw.physmem
    - freebsd-version
    
  install_script: 
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y bison postgresql10-server gmake libxml2 autoconf automake libtool pkgconf gettext iconv pcre gdal sfcgal geos libxslt cunit
  
  build_script:
    # will be removed
    - find . -name "*.pl" | xargs sed -i -r 's|/usr/bin/perl|/usr/bin/env perl|'
    - service postgresql oneinitdb
    - service postgresql onestart
    - su -l postgres -c "createuser -s `whoami`"
    - ./autogen.sh
    - ./configure CFLAGS="-I/usr/local/include -Wall -fno-omit-frame-pointer -Werror" LDFLAGS="-L/usr/local/lib"
    - gmake -j8
    - gmake -j8 check RUNTESTFLAGS=-v
    - gmake -j8 check RUNTESTFLAGS="-v --dumprestore"
    - gmake -j8 install
    - gmake -j8 installcheck RUNTESTFLAGS=-v
    - gmake -j8 installcheck RUNTESTFLAGS="-v --dumprestore"
